# NumPy basics

## Import convention

In [1]:
import numpy as np
np.random.seed(657743)

In [2]:
%pylab inline
plt.style.use('ggplot')

Populating the interactive namespace from numpy and matplotlib


## Creating arrays from Python sequences

In [3]:
# Core data structure in numpy
?np.ndarray

In [4]:
np.ndarray((2,2), dtype=np.float)

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

It kinda works, but is not very convenient.

In [5]:
?np.array

In [6]:
arr = np.array([[7, 2, 3], [3, 9, 6]])

In [7]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

Each array has `shape`, `size`:

In [8]:
print("Array shape is", arr.shape)
print("Array size is", arr.size)
print("Array has %i dimensions" % arr.ndim)

Array shape is (2, 3)
Array size is 6
Array has 2 dimensions


And `dtype`, `itemsize` and `nbytes`:

In [9]:
print("Array dtype is", arr.dtype)
print("Each item in the array takes %i bytes" % arr.itemsize)
print("Array takes %i bytes" % arr.nbytes)

Array dtype is int64
Each item in the array takes 8 bytes
Array takes 48 bytes


## Creating arrays of special shape and/or type

In [10]:
zeros_array = np.zeros((2,6), dtype=bool)
zeros_array

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [11]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

In [12]:
zeros_like_array = np.zeros_like(arr, dtype=np.complex128)
zeros_like_array

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [13]:
ones_array = np.ones((3,9), dtype=np.float32)
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [14]:
ones_like_array = np.ones_like(zeros_array, dtype=np.float32)
ones_like_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [15]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
range_array = np.arange(-5, 5)
range_array

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [17]:
range_array = np.arange(0, 5, 2)
range_array

array([0, 2, 4])

In [18]:
range_array = np.arange(0, 10, -2)

In [19]:
range_array

array([], dtype=int64)

In [20]:
range_array = np.arange(10, 0, -2)
range_array

array([10,  8,  6,  4,  2])

In [21]:
range_float_array = np.arange(-0.82, 5.32, 0.25)
range_float_array

array([-0.82, -0.57, -0.32, -0.07,  0.18,  0.43,  0.68,  0.93,  1.18,
        1.43,  1.68,  1.93,  2.18,  2.43,  2.68,  2.93,  3.18,  3.43,
        3.68,  3.93,  4.18,  4.43,  4.68,  4.93,  5.18])

## Basic indexing of numpy arrays

In [22]:
range_float_array[1]

-0.57

In [23]:
range_float_array[1:2]

array([-0.57])

In [24]:
range_float_array[:5]

array([-0.82, -0.57, -0.32, -0.07,  0.18])

In [25]:
range_float_array[-5:-2]

array([4.18, 4.43, 4.68])

In [26]:
range_float_array

array([-0.82, -0.57, -0.32, -0.07,  0.18,  0.43,  0.68,  0.93,  1.18,
        1.43,  1.68,  1.93,  2.18,  2.43,  2.68,  2.93,  3.18,  3.43,
        3.68,  3.93,  4.18,  4.43,  4.68,  4.93,  5.18])

In [27]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

In [28]:
arr[:1, 1:]

array([[2, 3]])

In [29]:
arr[0, 1:]

array([2, 3])

In [30]:
arr[0, ::2]

array([7, 3])

## Boolean and fancy indexing

In [31]:
random_array = np.random.randn(10)
random_array

array([-1.11204182,  0.46910808, -0.68408549,  0.69242926,  1.15223867,
        1.17339163, -0.11879617,  0.06423215, -1.2978598 , -0.64957899])

In [32]:
random_array>0

array([False,  True, False,  True,  True,  True, False,  True, False,
       False])

In [33]:
random_array[random_array>0]

array([0.46910808, 0.69242926, 1.15223867, 1.17339163, 0.06423215])

In [34]:
random_array[(random_array>0) | (random_array<-1)]

array([-1.11204182,  0.46910808,  0.69242926,  1.15223867,  1.17339163,
        0.06423215, -1.2978598 ])

In [35]:
random_array

array([-1.11204182,  0.46910808, -0.68408549,  0.69242926,  1.15223867,
        1.17339163, -0.11879617,  0.06423215, -1.2978598 , -0.64957899])

In [36]:
random_array[(random_array>0) & (random_array<1)]

array([0.46910808, 0.69242926, 0.06423215])

In [37]:
np.where(random_array>0)

(array([1, 3, 4, 5, 7]),)

In [38]:
ix0, = np.where(random_array>0)

In [39]:
ix0

array([1, 3, 4, 5, 7])

In [40]:
random_array[random_array>0]

array([0.46910808, 0.69242926, 1.15223867, 1.17339163, 0.06423215])

In [41]:
random_array[ix0]

array([0.46910808, 0.69242926, 1.15223867, 1.17339163, 0.06423215])

In [42]:
random_array = np.random.randn(3, 4)
random_array

array([[ 1.26308259,  1.10781119, -0.96620663,  0.7825883 ],
       [ 1.22047832,  1.28593266, -0.12777788,  0.36335958],
       [ 0.3168423 , -1.32085224, -0.91976381, -0.11364747]])

In [43]:
random_array[[0,2], [2, 3]]

array([-0.96620663, -0.11364747])

## View vs. copy

In [44]:
arr

array([[7, 2, 3],
       [3, 9, 6]])

In [45]:
arr_view = arr[:, :]
arr_copy = arr.copy()

In [46]:
arr_view

array([[7, 2, 3],
       [3, 9, 6]])

In [47]:
arr_copy

array([[7, 2, 3],
       [3, 9, 6]])

In [48]:
arr_view[1:, 1:] = 41

In [49]:
arr_view

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [50]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [51]:
arr_copy[1:, 1:] = 32

In [52]:
arr_copy

array([[ 7,  2,  3],
       [ 3, 32, 32]])

In [53]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

## Changing array shape

In [54]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [55]:
arr.reshape((1,6))

array([[ 7,  2,  3,  3, 41, 41]])

In [56]:
arr.reshape((6,-1))

array([[ 7],
       [ 2],
       [ 3],
       [ 3],
       [41],
       [41]])

In [57]:
arr.reshape((6,1,1))

array([[[ 7]],

       [[ 2]],

       [[ 3]],

       [[ 3]],

       [[41]],

       [[41]]])

In [58]:
np.expand_dims(arr, axis=1).shape

(2, 1, 3)

In [59]:
arr

array([[ 7,  2,  3],
       [ 3, 41, 41]])

In [60]:
arr.T

array([[ 7,  3],
       [ 2, 41],
       [ 3, 41]])

In [61]:
np.expand_dims(arr, axis=-1).shape

(2, 3, 1)

In [62]:
arr_t = np.transpose(np.expand_dims(arr, axis=-1), axes=(1,2,0))

In [76]:
np.expand_dims(arr.flatten(), axis=1)

array([[ 7],
       [ 2],
       [ 3],
       [ 3],
       [41],
       [41]])

## Changing array type

In [77]:
arr>2

array([[ True, False,  True],
       [ True,  True,  True]])

In [78]:
(arr>2).astype(np.int8)

array([[1, 0, 1],
       [1, 1, 1]], dtype=int8)

In [79]:
arr.astype(np.uint8)

array([[ 7,  2,  3],
       [ 3, 41, 41]], dtype=uint8)

In [80]:
arr.astype(np.float32)

array([[ 7.,  2.,  3.],
       [ 3., 41., 41.]], dtype=float32)

In [81]:
arr.astype(np.complex128)

array([[ 7.+0.j,  2.+0.j,  3.+0.j],
       [ 3.+0.j, 41.+0.j, 41.+0.j]])

## Stacking arrays

In [82]:
arr_1 = np.random.randint(10, size=(10,))
arr_2 = np.random.randint(10, size=(10,))

In [83]:
arr_1, arr_2

(array([9, 8, 2, 2, 1, 5, 3, 4, 2, 8]), array([0, 7, 6, 0, 2, 6, 6, 7, 0, 3]))

In [84]:
np.vstack([arr_1, arr_2])

array([[9, 8, 2, 2, 1, 5, 3, 4, 2, 8],
       [0, 7, 6, 0, 2, 6, 6, 7, 0, 3]])

In [85]:
np.hstack([arr_1, arr_2])

array([9, 8, 2, 2, 1, 5, 3, 4, 2, 8, 0, 7, 6, 0, 2, 6, 6, 7, 0, 3])

In [86]:
np.hstack([np.expand_dims(arr_1, 1), np.expand_dims(arr_2, 1)])

array([[9, 0],
       [8, 7],
       [2, 6],
       [2, 0],
       [1, 2],
       [5, 6],
       [3, 6],
       [4, 7],
       [2, 0],
       [8, 3]])

In [ ]:
arr_1.T

In [ ]:
np.vstack([arr_1, arr_2]).T

## Universal functions

For a full list of universal functions, see [ufunc reference](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html).

In [ ]:
arr_1

In [ ]:
arr_2

In [ ]:
arr

In [ ]:
arr.sum()

In [ ]:
arr.sum(axis=1)

In [ ]:
arr

In [ ]:
arr.sum(axis=1, keepdims=True)

In [ ]:
arr.mean(axis=0)

In [ ]:
arr_1, arr_2

In [ ]:
np.add(arr_1, arr_2, where=(arr_2<6))

In [ ]:
np.add(arr_1, arr_2, where=(arr_2<6), out=arr_2)

In [ ]:
arr_1

In [ ]:
arr_2